apiVersion: v1 
kind: ResourceQuota 
metadata:
  name: compute-qouta
  namespace: dev 

spec:
  hard:   
    pods: "15"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 9Gi
