apiVersion: v1
kind: Pod 
metadata:
  name: some-webapp 
spec:
   containers:
     image: ubuntu 
     securityContext:
       runAsUser: 1010
       capabilities: 
        add: ["SYS_TIME"]
     securityContext:
       runAsUser: 1000
