apiVersion: v1 
kind: ReplicationController 
metadata:
  name: redis
  labels:
    app: db 
spec:
  template:
    metadata:
      name: redis
      labels:
        app: db 
         
    spec:
       containers:
       - name: redis
         image:  redis

  replicas: 3         
