apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset 
  labels: 
     app: dummy-app  
     type: db
spec:
  template:
    metadata:
      name: redis-pod 
      labels:
        app: dummy-app
        type: db  
    spec: 
      containers: 
      - name: redis 
        image: redis 

  replicas: 4
  selector:
     matchLabels:
       app: dummy-app
       type: db
